services:
  multistream:
    build: .
    container_name: multi_stream
    ports:
      - "1935:1935"   # Ingest RTMP (OBS apunta aqui)
      - "8000:8000"   # API / panel HTTP
    env_file:
      - .env
    volumes:
      - ./config:/app/config
    restart: unless-stopped
